import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by doxygen2docusaurus from engine/docs/xml/, see config/doxygen2docusaurus.json
import doxygenSidebarCategoryJson from './sidebar-category-doxygen.json';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// The item type is not exported from the package root, so take it off the sidebar array
type SidebarItemConfig = Extract<SidebarsConfig[string], unknown[]>[number];

// A JSON import widens every `type` to `string`, so the shape is restated once here
const doxygenSidebarCategory = doxygenSidebarCategoryJson as SidebarItemConfig;

/**
 * doxygen2docusaurus reuses the same labels under different parents ('Hierarchy',
 * 'All', 'Variables'), which collides in the i18n translation files. Give every item
 * an explicit key: the doc id where there is one, otherwise its path in the tree —
 * both stay stable across regeneration.
 */
function withSidebarKeys(
  item: SidebarItemConfig,
  path = '',
): SidebarItemConfig {
  // Shorthands carry no label of their own, so they cannot collide
  if (typeof item === 'string' || typeof item.type !== 'string') {
    return item;
  }

  const key =
    item.type === 'doc' || item.type === 'ref'
      ? item.id
      : `${path}/${'label' in item ? item.label : item.type}`;

  if (item.type === 'category' && Array.isArray(item.items)) {
    return {
      ...item,
      key,
      items: item.items.map((child) => withSidebarKeys(child, key)),
    };
  }

  return {...item, key};
}

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Engine API reference, generated from the engine's Doxygen XML
  apiSidebar: [withSidebarKeys(doxygenSidebarCategory)],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
