import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Generated by doxygen2docusaurus from engine/docs/xml/, see config/doxygen2docusaurus.json
import doxygenSidebarCategory from './sidebar-category-doxygen.json';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

type DoxygenSidebarItem = {
  label?: string;
  id?: string;
  key?: string;
  items?: DoxygenSidebarItem[];
};

/**
 * doxygen2docusaurus reuses the same labels under different parents ('Hierarchy',
 * 'All', 'Variables'), which collides in the i18n translation files. Give every item
 * an explicit key: the doc id where there is one, otherwise its path in the tree —
 * both stay stable across regeneration.
 */
function withSidebarKeys(
  item: DoxygenSidebarItem,
  path = '',
): DoxygenSidebarItem {
  const key = item.id ?? `${path}/${item.label ?? ''}`;

  return {
    ...item,
    key,
    ...(item.items && {
      items: item.items.map((child) => withSidebarKeys(child, key)),
    }),
  };
}

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Engine API reference, generated from the engine's Doxygen XML
  apiSidebar: [
    withSidebarKeys(doxygenSidebarCategory),
  ] as unknown as SidebarsConfig[string],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
